// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:LanChat.MessageSystem")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow.Chat_Page._MSGS_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow.Chat_Page._cACV_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow.Chat_Page._cNAV_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow.Chat_Page._mPNL_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow.Chat_Page._INPT_")]
[assembly: SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:LanChat.MessageSystem.Renderer.lIDX")]
[assembly: SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:LanChat.MessageSystem.Renderer.uIDX")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Batch.Exclude(System.Int32)~LanChat.MessageSystem.Message")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.App._EXIT_(LanChat.Runtime.App.Integration,System.Windows.Window)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.App._MAIN_(System.Windows.Window)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.App._INIT_(System.Windows.Window)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.InitWindow._APP_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.App._TERM_(System.Windows.Window)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.MessageSystem.Messager._NAME_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.MessageSystem.Messager._OFST_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Batch._INCD_(LanChat.MessageSystem.Message)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Batch._DELT_(System.Int32)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Batch._EXLD_~LanChat.MessageSystem.Message")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Batch._EXLD_~LanChat.MessageSystem.Message")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Messager.Read(System.Int32)~LanChat.MessageSystem.Batch")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Runtime._AUTH_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Runtime._STRT_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Runtime._STOP_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Runtime._TIME_~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:LanChat.NetworkSystem")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:LanChat.SerialSystem")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:LanChat.InputSystem")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.InputSystem.Listener.#ctor(System.ValueTuple{System.Windows.Input.Key,System.Action[]}[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LanChat.Runtime.MainWindow._APP_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Runtime._TIME_~System.Nullable{System.DateTime}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._STRT_(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._CNCT_(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._SEND_(System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._COMM_~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1835:Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._COMM_~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._DCVR_(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Client_RUNTIME._DCVR_")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._SEND_(System.Net.Sockets.NetworkStream,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._SEND_(System.Net.Sockets.NetworkStream,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._COMM_(System.Net.Sockets.TcpClient,System.UInt32)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._DCVR_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._PROC_")]
[assembly: SuppressMessage("Performance", "CA1835:Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.NetworkSystem.Server_RUNTIME._COMM_(System.Net.Sockets.TcpClient,System.UInt32)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Messager._SEND_CLIENT_(System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Messager._NEXT_CLIENT_(System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Messager._SEND_SERVER_(System.Net.Sockets.NetworkStream,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.MessageSystem.Messager._RQST_SERVER_(System.Net.Sockets.NetworkStream,System.String[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.MainWindow._lINIT_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.Runtime.MainWindow._cINIT_")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:LanChat.SubSystem.UserInterface.uiPage")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:LanChat.SubSystem.Network.Runtime.rtEntity")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:LanChat.SubSystem.Network.Runtime.rtClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:LanChat.SubSystem.Network.Runtime.rtServer")]
[assembly: SuppressMessage("Performance", "CA1835:Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.SubSystem.Network.Runtime.rtClient._COMM_~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.SubSystem.Network.Runtime.rtClient._COMM_~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1835:Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.SubSystem.Network.Runtime.rtServer._COMM_(System.Net.Sockets.TcpClient)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:LanChat.SubSystem.Network.Runtime.rtServer._COMM_(System.Net.Sockets.TcpClient)~System.Threading.Tasks.Task")]
